name: LinspirerDemo
description: LinspirerDemo
meta_description: "Linspirer_Demo"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: ""
domain_name: "youngtoday.github.io"
google_analytics: "UA-XXXXXXXX-X"
plugins: [jekyll-paginate]

# Details for the RSS feed generator
url: ""
author: "YoungToday"

# Disqus config
disqus-shortname: ""
